### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by KaoImin** [nervosnetwork/overlord#27]
- [x] feat: Wal mod
- [ ] feat: integration tests
- [x] refactor: only next leader will wait for block interval delay
- [x] refactor: do commit when receiving a precommitQC that hash is not null
- [x] refactor: structured log output
